version: "3"
services:
  account:
    build:
      context: .
      dockerfile: ./services/account/app.dockerfile
    depends_on:
      - account_db
    environment:
      - DATABASE_URL=postgres://suryansh:123456@account_db/suryansh?sslmode=disable
    restart: on_failure

  catalog:
    build:
      context: .
      dockerfile: ./services/catalog/app.dockerfile
    depends_on:
      - catalog_db
    environment:
      - DATABASE_URL=http://catalog_db:9200
    restart: on_failure

  order:
    build:
      context: .
      dockerfile: ./services/order/app.dockerfile
    depends_on:
      - order_db
    environment:
      - DATABASE_URL=postgres://suryansh:123456@order_db/suryansh?sslmode=disable
      - ACCOUNT_SERVICE_URL=account:8080
      - CATALOG_SERVICE_URL=catalog:8080
    restart: on_failure

  graphql:
    build:
      context: .
      dockerfile: ./services/graphql/app.dockerfile
    ports:
      - 8000:8080
    depends_on:
      - account
      - catalog
      - order
    environment:
      - ACCOUNT_SERVICE_URL=account:8080
      - CATALOG_SERVICE_URL=catalog:8080
      - ORDER_SERVICE_URL=order:8080
    restart: on_failure
    
  account_db:
  catalog_db:
  order_db:
  